name: cicd_saint_of_the_day

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout saint_script
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install poetry
      run: |
          python -m pip install --upgrade pip
          pip install poetry

    - name: install dependencies
      run: poetry install
  
  run_saint_script:
    runs-on: ubuntu-latest
    steps:
      env:
        host: ${{ secrets.host }}
        dbname: ${{ secrets.dbname }}
        user: ${{ secrets.user }}
        password: ${{ secrets.password }}
        port: ${{ secrets.port }}
      run: saint_script.py
