name: continuous_integration_saint

on: push
#  schedule:
#    - cron: '*/1 * * * *'  #0 0 */1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

  script:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: run saint_script
        env:
          URI: ${{secrets.URI}}
        run: saint_script.py

   