name: continuous_integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
      
      - name: Install Poetry
        run: pip install poetry
      
      - name: Install Dependencies
        run: poetry install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        run: pip install poetry
      
      - name: Install Dependencies
        run: 
          poetry install

      - name: test_script
        run: poetry run pytest
  
  coverage:
    runs-on: ubuntu-latest
    needs: [build,test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        run: pip install poetry
      
      - name: Install Dependencies
        run: | 
            poetry install
      
      - name: code_coverage
        run: poetry run pytest --cov=gspread_code --cov=test_gspread_code 