name: continuous_integration_saint

on:
  schedule:
    - cron: '0 2 */1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Print current directory
        run: |
          pwd

      - name: run saint_script
        env:
          URI: ${{secrets.URI}}

        run: |
          echo $URI
          poetry run saints_script

   